name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v3
      - run: docker build -t dencoseca/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dencoseca/react-test npm test

      - run: docker build -t dencoseca/multi-client ./client
      - run: docker build -t dencoseca/multi-nginx ./nginx
      - run: docker build -t dencoseca/multi-server ./server
      - run: docker build -t dencoseca/multi-worker ./worker

      - run: docker push dencoseca/multi-client
      - run: docker push dencoseca/multi-nginx
      - run: docker push dencoseca/multi-server
      - run: docker push dencoseca/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: aws-elasticbeanstalk-multi-docker-app
          environment_name: aws-elasticbeanstalk-multi-docke-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-728579894677
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
