name: Deploy MultiK8s
on:
  workflow_dispatch:
    
env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: |-
          docker build -t dencoseca/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true dencoseca/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-396219

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: europe-west1-c

      - name: Build
        run: |-
          docker build -t dencoseca/multi-client-k8s-gh:latest -t dencoseca/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t dencoseca/multi-server-k8s-gh:latest -t dencoseca/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t dencoseca/multi-worker-k8s-gh:latest -t dencoseca/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push dencoseca/multi-client-k8s-gh:latest
          docker push dencoseca/multi-server-k8s-gh:latest
          docker push dencoseca/multi-worker-k8s-gh:latest
          
          docker push dencoseca/multi-client-k8s-gh:${{ env.SHA }}
          docker push dencoseca/multi-server-k8s-gh:${{ env.SHA }}
          docker push dencoseca/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=dencoseca/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=dencoseca/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=dencoseca/multi-worker-k8s-gh:${{ env.SHA }}
